#dnf module disable nginx -y
#dnf module enable nginx:1.24 -y
#dnf install nginx -y
#cp nginx.conf /etc/nginx/nginx.conf
#rm -rf /usr/share/nginx/html/*
#curl -o /tmp/frontend.zip https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
#cd /usr/share/nginx/html
#unzip /tmp/frontend.zip
#  # create nginx file
#systemctl enable nginx
#systemctl restart nginx

- name: Disable nginx
  ansible.builtin.shell: dnf module disable nginx -y

#- name: Enable nginx version 1.24
#  ansible.builtin.shell: dnf module enable nginx -y

- name: Reset nginx module
  command: dnf module reset nginx -y

- name: Enable nginx module stream 1.24
  command: dnf module enable nginx:1.24 -y

- name: Install the nginx
  ansible.builtin.dnf:
    name: nginx
    state: installed

- name: Copy nginx config
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Remove nginx default content
  ansible.builtin.file:
    path: /usr/share/nginx/html/*
    state: absent

- name: Create nginx directory
  ansible.builtin.file:
    path: /usr/share/nginx/html/*
    state: directory

- name: Unarchive content from HTTPS URL
  ansible.builtin.unarchive:
    src: "https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip"
    dest: /usr/share/nginx/html/
    remote_src: yes

- name: Enable Nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted
    enabled: true

